services:
  postgres:
    image: postgres:17

    container_name: gym-tracker-postgres

    env_file:
      - .env.development

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - gym-tracker-backend-network

  migrate:
    image: maiminhthang/gym-tracker-api-dev

    env_file:
      - .env.development

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - gym-tracker-backend-network

    command: >
      dotnet ef database update

  backend:
    image: maiminhthang/gym-tracker-api

    container_name: gym-tracker-api

    env_file:
      - .env.development

    ports:
      - "5078:8080"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - gym-tracker-backend-network

volumes:
  postgres-data:

networks:
  gym-tracker-backend-network:
    driver: bridge
